name: Mix Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: 1.8.2
            otp: 20.3.8.26
          - elixir: 1.9.4
            otp: 20.3.8.26
          - elixir: 1.10.4
            otp: 21.3.8.16
          - elixir: 1.10.4
            otp: 23.0.3
          - elixir: 1.11.0
            otp: 23.0.3
          - elixir: 1.11.0
            otp: 22.2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Format, Credo, Coveralls
        env:
          MIX_ENV: test
        run: | 
          export MIX_ENV=test
          mix format --check-formatted --dry-run
          mix deps.get
          mix deps.compile
          mix compile --warnings-as-errors
          mix credo --strict
          mix coveralls

